services:
  web: 
    build:
      context: app
      target: dev-envs
    stop_signal: SIGINT
    ports: 
      - '5000:5000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - C:\Temp\mnt\dev:/mnt/dev
      - C:\Temp\mnt\qa:/mnt/qa
      - C:\Temp\mnt\released:/mnt/released
