services:
  web: 
    build:
      context: app
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '5000:5000'
    volumes:
      - C:\Temp\mnt\dev:/mnt/dev
      - C:\Temp\mnt\qa:/mnt/qa
      - C:\Temp\mnt\released:/mnt/released
